// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "marlo":return img`
. . . . . 2 2 2 2 . . . . . . . 
. . . . 2 2 2 2 2 2 2 2 2 . . . 
. . . . e e e d d e d . . . . . 
. . . e d e d d d e d d d . . . 
. . . e d e e d d d e d d d . . 
. . . e e d d d d e e e e . . . 
. . . . . d d d d d d d . . . . 
. . . . e e 2 e e e . . . . . . 
. . . e e e 2 e e 2 e e e . . . 
. . e e e e 2 2 2 2 e e e e . . 
. . d d e 2 d 2 2 d 2 e d d . . 
. . d d d 2 2 2 2 2 2 d d d . . 
. . d d 2 2 2 2 2 2 2 2 d d . . 
. . . . 2 2 2 . . 2 2 2 . . . . 
. . . e e e . . . . e e e . . . 
. . e e e e . . . . e e e e . . 
`;
            case "image3":
            case "myImage0":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image5":
            case "marlo0":return img`
................
................
................
................
................
................
.....2222.......
....222222222...
....eeedded.....
...ededddeddd...
...edeedddeddd..
...eeddddeeee...
.....ddddddd....
....ee2eee......
...eee2ee2eee...
..eeee2222eeee..
..eee2d22d2eee..
..eee222222eee..
..eee222222eee..
..eee222222eee..
..dde222222edd..
..ddd222222ddd..
..dd22222222dd..
....222..222....
....222..222....
....222..222....
...eee....eee...
...eee....eee...
..eeee....eeee..
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
`;
            case "image6":
            case "marlo1":return img`
................
................
................
................
................
.....2222.......
....222222222...
....eeedded.....
...ededddeddd...
...edeedddeddd..
...eeddddeeee...
.....ddddddd....
....ee2eee......
...eee2ee2eee...
..eeee2222eeee..
..eee2d22d2eee..
..eee222222eee..
..eee222222eee..
..eee222222eee..
..dde222222edd..
..ddd222222ddd..
..dd22222222dd..
....222..222....
....222..222....
....222..222....
...eee....eee...
...eee....eee...
..eeee....eeee..
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
`;
            case "image2":
            case "myImage":return img`
. . . . 2 2 2 2 1 1 1 1 . . . . 
. . . 1 2 2 2 2 1 1 1 1 1 . . . 
. . 1 1 1 2 2 2 2 1 1 1 1 1 . . 
. 1 1 1 1 2 2 2 2 2 1 1 1 1 1 . 
. 2 1 1 2 2 2 2 2 2 2 1 1 1 2 . 
2 2 2 2 2 2 1 1 1 2 2 2 2 2 2 2 
2 2 2 2 2 1 1 1 1 1 2 2 2 2 2 1 
1 2 2 2 1 1 1 1 1 1 1 2 2 2 1 1 
1 1 2 2 d d d d d d d d 2 2 1 1 
. 1 2 d d f f d d f f d d 2 2 . 
. . . d d f f d d f f d d . . . 
. . . d d f f d d f f d d . . . 
. . . d d f f d d f f d d . . . 
. . . d d d d d d d d d d . . . 
. . . d d d d d d d d d d . . . 
. . . . d d d d d d d d . . . . 
`;
            case "image4":
            case "myImage1":return img`
. . . . e e e e e e e e . . . . 
. . . e e e e e e e e e e . . . 
. . e e e e e e e e e e e e . . 
. e e e e e e e e e e e e e e . 
. e e e e e e e e e e e e e e . 
e e e e e e e e e e e e e e e e 
e e e e e e e e e e e e e e e e 
e e e e e e e e e e e e e e e e 
e e e e d d d d d d d d e e e e 
. e e d d f f d d f f d d e e . 
. . . d d f f d d f f d d . . . 
. . . d d d d d d d d d d . . . 
. . . d d f f f f f f d d . . . 
. . . d f d d d d d 1 f d . . . 
. . e e d d d d d d d d e e . . 
. e e e e d d d d d d e e e e . 
`;
            case "image8":
            case "marlo3":return img`
................
................
................
................
................
.......2222.....
...222222222....
.....deddeee....
...dddedddede...
..dddedddeede...
...eeeeddddee...
....ddddddd.....
......eee2ee....
...eee2ee2eee...
..eeee2222eeee..
..eee2d22d2eee..
..eee222222eee..
..eee222222eee..
..eee222222eee..
..dde222222edd..
..ddd222222ddd..
..dd22222222dd..
....222..222....
....222..222....
....222..222....
...eee....eee...
...eee....eee...
..eeee....eeee..
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
`;
            case "image7":
            case "marlo2":return img`
. . . . . . . 2 2 2 2 . . . . . 
. . . 2 2 2 2 2 2 2 2 2 . . . . 
. . . . . d e d d e e e . . . . 
. . . d d d e d d d e d e . . . 
. . d d d e d d d e e d e . . . 
. . . e e e e d d d d e e . . . 
. . . . d d d d d d d . . . . . 
. . . . . . e e e 2 e e . . . . 
. . . e e e 2 e e 2 e e e . . . 
. . e e e e 2 2 2 2 e e e e . . 
. . d d e 2 d 2 2 d 2 e d d . . 
. . d d d 2 2 2 2 2 2 d d d . . 
. . d d 2 2 2 2 2 2 2 2 d d . . 
. . . . 2 2 2 . . 2 2 2 . . . . 
. . . e e e . . . . e e e . . . 
. . e e e e . . . . e e e e . . 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
